name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        with:
          github_user_name: fernandobandeira
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=orange&color_dots=#d0d0d0,#1c7111,#2eaa1f,#46e133,#1dff00

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
